---
- include_tasks: preflight.yml

- include_tasks: upgrade.yml
  when:
    - _loki_plugin.installed
    - _loki_plugin.version != docker_loki_version

- include_tasks: install.yml
  when:
    - not _loki_plugin.installed
