---
- name: Disable loki plugin
  command: "docker plugin disable --force {{ _docker_loki_alias }}"
  args:
    warn: false
  tags:
    - skip_ansible_lint
- name: Upgrade loki plugin
  command: >
    docker plugin upgrade
    --grant-all-permissions --skip-remote-check
    {{ _docker_loki_alias }}
    {{ docker_loki_image }}:{{ docker_loki_version }}
  args:
    warn: false
  notify:
    - restart docker
  tags:
    - skip_ansible_lint
- name: Enable loki plugin
  command: "docker plugin enable {{ _docker_loki_alias }}"
  args:
    warn: false
  tags:
    - skip_ansible_lint
