---
- name: Show what we will do
  debug:
    msg: "{{ docker_loki_image }}:{{ docker_loki_version }}"

- name: Upgrade
  loki_setup:
    name: "{{ _docker_loki_alias }}"
    version: "{{ docker_loki_image }}:{{ docker_loki_version }}"
    state: upgrade
  register: _loki_upgrade
  notify:
    - restart docker

- name: Show upgrade
  debug:
    var: _loki_upgrade
