---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: Update yum
      command: yum makecache
      args:
        warn: false
    - name: Install dependencies
      yum:
        name:
          - curl
          - jq
          - python-pip
    - name: Pre-install a docker requirement (workaround for python2 and docker=4.4.4)
      pip:
        name: websocket-client
        version: "<1"
  roles:
    # Install Docker
    - role: atosatto.docker-swarm
      vars:
        docker_daemon_config:
          storage-driver: vfs
        docker_py_package_version: 4.4.4
        docker_service_override: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd -H unix://
        skip_cli: False
        skip_containerd: False
        skip_docker_compose: True
        skip_docker_py: False
        skip_engine: False
        skip_group: True
        skip_swarm: False
    # Install loki-driver plugin
    - role: ansible-docker-plugin-loki
      vars:
        # older tags are prefixed with 'v'
        docker_loki_version: v1.2.0
    # Configure loki-driver plugin
    # TODO: should this be done different?
    - role: atosatto.docker-swarm
      vars:
        docker_daemon_config:
          storage-driver: vfs
          log-driver: loki
        skip_cli: True
        skip_containerd: True
        skip_docker_compose: True
        skip_docker_py: True
        skip_engine: True
        skip_group: True
        skip_swarm: True
  post_tasks:
    - name: Start service which sends logs
      docker_swarm_service:
        name: random-logger
        image: chentex/random-logger:latest
        restart_config:
          condition: any
