---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: Update yum
      command: yum makecache
      args:
        warn: false
    - name: Install dependencies
      yum:
        name:
          - curl
          - jq
  roles:
    - role: atosatto.docker-swarm
      vars:
        docker_daemon_config:
          storage-driver: vfs
        docker_service_override: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd -H unix://
        skip_cli: False
        skip_containerd: False
        skip_docker_compose: True
        skip_docker_py: False
        skip_engine: False
        skip_group: True
        skip_swarm: True
