---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: Update yum
      command: yum makecache
      args:
        warn: false
    - name: Install test dependencies
      yum:
        name:
          - curl
          - jq
          - python-pip
    - name: Pre-install a docker requirement (workaround for python2 and docker=4.4.4)
      pip:
        name: websocket-client
        version: "<1"
  roles:
    - role: atosatto.docker-swarm
      vars:
        docker_daemon_config:
          storage-driver: vfs
        docker_py_package_version: 4.4.4
        docker_service_override: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd -H unix://
        skip_docker_compose: True
        skip_group: True
        skip_swarm: True
